---
title: "hw1"
author: "SeungMin"
date: "2019년 3월 7일"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/wjssm/Desktop/0.graduate/3rd/Statistical_Graphics/hw/hw1")
library(tidyverse)

```

#1
```{r}
ggplot(mpg) + geom_point(aes(cyl, hwy))
```

#2
```{r}
ggplot(mpg) + geom_point(aes(drv, class))
```

drv, class 모두 categorical 변수이기 때문에

#3
```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))

ggplot(mpg) + geom_point(aes(displ, hwy),color = 'blue')
```

mapping 안에 blue를 써서 안 바뀜. 밖에 써줘야 blue로 색이 바뀜

#4
```{r}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(drv ~ .)

ggplot(data = mpg) +
geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(. ~ cyl)
```

facet_grid(y~x) 이므로, 첫번째 그래프에서 y값만 drv로 지정해주면, y축을 drv의 값에 따라 나눠서 플럿을 그리고, x값은 원래 축인 displ로 그대로이다. 또한, 두번째 그래프에서는 x값만 cyl로 지정해주어, cyl값에 따라 x축을 나누고 y축은 displ그대로이다. 따라서 여기서 '.'은 원래 축 그대로 두라는 의미를 갖는다.


#5
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) +
  geom_point() + geom_smooth()

ggplot() + geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))
```

다르지 않다. 같다. ggplot(data = , aes(x = , y = )) 에 미리 지정해주면 뒤에 geom_ 함수에 다 영향을 미치므로. 한 번만 선언해줘도 매번 선언해주는 것과 같은 결과.

#6
```{r}
ggplot(mpg, aes(displ, hwy)) + geom_point() +
  geom_smooth(se = F, aes(group = drv))

ggplot(mpg, aes(displ,hwy))  + geom_point(size = 4, color = 'white')+ geom_point(aes(color = drv))
```